import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { StoreProvider } from '@/shared/providers/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AntdRegistry>
                    <StoreProvider>{children}</StoreProvider>
                </AntdRegistry>
            </body>
        </html>
    )
}
